name: workiom_test_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.1.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.9.1
  retrofit_generator: ^10.2.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2 
  easy_localization: ^3.0.8
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_gen: ^5.12.0 
  go_router: ^17.0.0
  device_preview: ^1.3.1
  flutter_timezone: ^5.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  flutter_gen_runner: ^5.12.0

  flutter_test:
    sdk: flutter
  

  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21

# --------------------------------  flutter_gen
flutter_gen:
  output: lib/core/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true

  colors:
    inputs:
      - assets/colors/colors.xml


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
